/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace EvidenceCustody {
      
    export type TransferStruct = {evidenceId: BytesLike, evidenceHash: BytesLike, fromAgency: BytesLike, toAgency: BytesLike, createdAt: BigNumberish, confirmedAt: BigNumberish, createdBy: AddressLike, confirmedBy: AddressLike, status: BigNumberish}

    export type TransferStructOutput = [evidenceId: string, evidenceHash: string, fromAgency: string, toAgency: string, createdAt: bigint, confirmedAt: bigint, createdBy: string, confirmedBy: string, status: bigint] & {evidenceId: string, evidenceHash: string, fromAgency: string, toAgency: string, createdAt: bigint, confirmedAt: bigint, createdBy: string, confirmedBy: string, status: bigint }
  
    }

  export interface EvidenceCustodyInterface extends Interface {
    getFunction(nameOrSignature: "anchorEvidence" | "authorizedAgencies" | "confirmTransfer" | "createTransfer" | "getEvidenceAnchor" | "getTransfer" | "owner" | "setAgencyAuthorization"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AgencyAuthorizationUpdated" | "EvidenceAnchored" | "TransferConfirmed" | "TransferCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'anchorEvidence', values: [BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'authorizedAgencies', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'confirmTransfer', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'createTransfer', values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'getEvidenceAnchor', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getTransfer', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAgencyAuthorization', values: [BytesLike, boolean]): string;

    decodeFunctionResult(functionFragment: 'anchorEvidence', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authorizedAgencies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEvidenceAnchor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAgencyAuthorization', data: BytesLike): Result;
  }

  
    export namespace AgencyAuthorizationUpdatedEvent {
      export type InputTuple = [agencyId: BytesLike, authorized: boolean];
      export type OutputTuple = [agencyId: string, authorized: boolean];
      export interface OutputObject {agencyId: string, authorized: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EvidenceAnchoredEvent {
      export type InputTuple = [evidenceId: BytesLike, evidenceHash: BytesLike, timestamp: BigNumberish, anchoredBy: AddressLike];
      export type OutputTuple = [evidenceId: string, evidenceHash: string, timestamp: bigint, anchoredBy: string];
      export interface OutputObject {evidenceId: string, evidenceHash: string, timestamp: bigint, anchoredBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferConfirmedEvent {
      export type InputTuple = [transferId: BytesLike, evidenceId: BytesLike, timestamp: BigNumberish, confirmedBy: AddressLike];
      export type OutputTuple = [transferId: string, evidenceId: string, timestamp: bigint, confirmedBy: string];
      export interface OutputObject {transferId: string, evidenceId: string, timestamp: bigint, confirmedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TransferCreatedEvent {
      export type InputTuple = [transferId: BytesLike, evidenceId: BytesLike, fromAgency: BytesLike, toAgency: BytesLike, evidenceHash: BytesLike, timestamp: BigNumberish, createdBy: AddressLike];
      export type OutputTuple = [transferId: string, evidenceId: string, fromAgency: string, toAgency: string, evidenceHash: string, timestamp: bigint, createdBy: string];
      export interface OutputObject {transferId: string, evidenceId: string, fromAgency: string, toAgency: string, evidenceHash: string, timestamp: bigint, createdBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EvidenceCustody extends BaseContract {
    
    connect(runner?: ContractRunner | null): EvidenceCustody;
    waitForDeployment(): Promise<this>;

    interface: EvidenceCustodyInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    anchorEvidence: TypedContractMethod<
      [evidenceId: BytesLike, evidenceHash: BytesLike, agencyId: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    authorizedAgencies: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    confirmTransfer: TypedContractMethod<
      [transferId: BytesLike, receivingAgency: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    createTransfer: TypedContractMethod<
      [transferId: BytesLike, evidenceId: BytesLike, fromAgency: BytesLike, toAgency: BytesLike, evidenceHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getEvidenceAnchor: TypedContractMethod<
      [evidenceId: BytesLike, ],
      [[string, bigint, string, boolean] & {evidenceHash: string, timestamp: bigint, anchoredBy: string, exists: boolean }],
      'view'
    >
    

    
    getTransfer: TypedContractMethod<
      [transferId: BytesLike, ],
      [EvidenceCustody.TransferStructOutput],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setAgencyAuthorization: TypedContractMethod<
      [agencyId: BytesLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'anchorEvidence'): TypedContractMethod<
      [evidenceId: BytesLike, evidenceHash: BytesLike, agencyId: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'authorizedAgencies'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'confirmTransfer'): TypedContractMethod<
      [transferId: BytesLike, receivingAgency: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createTransfer'): TypedContractMethod<
      [transferId: BytesLike, evidenceId: BytesLike, fromAgency: BytesLike, toAgency: BytesLike, evidenceHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getEvidenceAnchor'): TypedContractMethod<
      [evidenceId: BytesLike, ],
      [[string, bigint, string, boolean] & {evidenceHash: string, timestamp: bigint, anchoredBy: string, exists: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getTransfer'): TypedContractMethod<
      [transferId: BytesLike, ],
      [EvidenceCustody.TransferStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setAgencyAuthorization'): TypedContractMethod<
      [agencyId: BytesLike, authorized: boolean, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AgencyAuthorizationUpdated'): TypedContractEvent<AgencyAuthorizationUpdatedEvent.InputTuple, AgencyAuthorizationUpdatedEvent.OutputTuple, AgencyAuthorizationUpdatedEvent.OutputObject>;
getEvent(key: 'EvidenceAnchored'): TypedContractEvent<EvidenceAnchoredEvent.InputTuple, EvidenceAnchoredEvent.OutputTuple, EvidenceAnchoredEvent.OutputObject>;
getEvent(key: 'TransferConfirmed'): TypedContractEvent<TransferConfirmedEvent.InputTuple, TransferConfirmedEvent.OutputTuple, TransferConfirmedEvent.OutputObject>;
getEvent(key: 'TransferCreated'): TypedContractEvent<TransferCreatedEvent.InputTuple, TransferCreatedEvent.OutputTuple, TransferCreatedEvent.OutputObject>;

    filters: {
      
      'AgencyAuthorizationUpdated(bytes32,bool)': TypedContractEvent<AgencyAuthorizationUpdatedEvent.InputTuple, AgencyAuthorizationUpdatedEvent.OutputTuple, AgencyAuthorizationUpdatedEvent.OutputObject>;
      AgencyAuthorizationUpdated: TypedContractEvent<AgencyAuthorizationUpdatedEvent.InputTuple, AgencyAuthorizationUpdatedEvent.OutputTuple, AgencyAuthorizationUpdatedEvent.OutputObject>;
    

      'EvidenceAnchored(bytes32,bytes32,uint64,address)': TypedContractEvent<EvidenceAnchoredEvent.InputTuple, EvidenceAnchoredEvent.OutputTuple, EvidenceAnchoredEvent.OutputObject>;
      EvidenceAnchored: TypedContractEvent<EvidenceAnchoredEvent.InputTuple, EvidenceAnchoredEvent.OutputTuple, EvidenceAnchoredEvent.OutputObject>;
    

      'TransferConfirmed(bytes32,bytes32,uint64,address)': TypedContractEvent<TransferConfirmedEvent.InputTuple, TransferConfirmedEvent.OutputTuple, TransferConfirmedEvent.OutputObject>;
      TransferConfirmed: TypedContractEvent<TransferConfirmedEvent.InputTuple, TransferConfirmedEvent.OutputTuple, TransferConfirmedEvent.OutputObject>;
    

      'TransferCreated(bytes32,bytes32,bytes32,bytes32,bytes32,uint64,address)': TypedContractEvent<TransferCreatedEvent.InputTuple, TransferCreatedEvent.OutputTuple, TransferCreatedEvent.OutputObject>;
      TransferCreated: TypedContractEvent<TransferCreatedEvent.InputTuple, TransferCreatedEvent.OutputTuple, TransferCreatedEvent.OutputObject>;
    
    };
  }